# Copyright (c) 2016, Linaro Limited
# All rights reserved.
# SPDX-License-Identifier:     BSD-3-Clause



language: c
compiler: clang
sudo: required

before_install:
        - sudo apt-get -qq update
        - sudo apt-get install automake autoconf libtool libssl-dev graphviz mscgen doxygen
        - gem install asciidoctor

#       Install cunit for the validation tests because distro version is too old and fails C99 compile
        - export CUNIT_VERSION=2.1-3
        - curl -sSOL http://sourceforge.net/projects/cunit/files/CUnit/${CUNIT_VERSION}/CUnit-${CUNIT_VERSION}.tar.bz2
        - tar -jxf *.bz2
        - cd CUnit*
        - ./bootstrap
        - ./configure --enable-debug --enable-automated --enable-basic --enable-console --enable-examples --enable-test
        - make
        - sudo make install
        - cd ..
        - export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"

install:
        - ./bootstrap

script:
        - ./configure --enable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-user-guides --enable-test-perf-proc --enable-test-example
        - make check
        - make doxygen-doc
        - make distcheck
